server:
  address: localhost
  port: 8082

spring:
  application.name: contract-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloudchain?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password:

  jpa:
    show-sql: true
    generate-ddl: true
    hibernate.ddl-auto: update
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties.hibernate:
      show_sql: true
      format_sql: true
      use_sql_comments: true

feign:
  hystrix.enabled: true
  client:
    config:
      default:
        connect-timeout: 30000
        read-timeout: 30000

cloud:
  aws:
    region:
      static: ap-northeast-2
    s3:
      bucket: pnu-studyhub
    #    credentials:
    #      accessKey: ${STUDYHUB_S3_ACCESS_KEY}
    #      secretKey: ${STUDYHUB_S3_SECRET_KEY}
    stack:
      auto: false

logging:
  level:
    org.hibernate: INFO