apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: contract
  namespace: {{ .Values.global.namespace}}
spec:
  project: default
  source:
    repoURL: {{ .Values.global.repoURL }}
    targetRevision: argocd
    path: contract
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
